#!/usr/bin/env python3
"""
Setup Supabase tables for prompt validation.
Run this once to create the schema.
"""
import os
from supabase import create_client

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    raise ValueError("Set SUPABASE_URL and SUPABASE_KEY environment variables")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# SQL to create tables - run this in Supabase SQL Editor
SQL_SCHEMA = """
-- Interpretations generated by LLM
CREATE TABLE IF NOT EXISTS interpretations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    instrument_code TEXT NOT NULL,
    score INTEGER NOT NULL,
    level TEXT NOT NULL,
    prompt_variant TEXT NOT NULL,
    user_profile_id INTEGER,
    interpretation_text TEXT NOT NULL,
    model TEXT DEFAULT 'gpt-4.1',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Evaluations by human reviewers (blind test)
CREATE TABLE IF NOT EXISTS evaluations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    interpretation_id UUID REFERENCES interpretations(id),
    evaluator_name TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    preferred_over UUID REFERENCES interpretations(id),
    feedback TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_interpretations_instrument ON interpretations(instrument_code);
CREATE INDEX IF NOT EXISTS idx_interpretations_variant ON interpretations(prompt_variant);
CREATE INDEX IF NOT EXISTS idx_evaluations_evaluator ON evaluations(evaluator_name);
"""

print("=== Supabase Schema ===")
print("Copy and run this SQL in your Supabase SQL Editor:")
print("https://supabase.com/dashboard/project/_/sql")
print()
print(SQL_SCHEMA)
print()
print("After running the SQL, this script will verify the connection...")

# Test connection
try:
    result = supabase.table("interpretations").select("id").limit(1).execute()
    print("✅ Connection successful! Tables exist.")
except Exception as e:
    print(f"⚠️  Tables not yet created or connection error: {e}")
    print("Run the SQL above first, then re-run this script.")
